[package]
name = "vibers"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.3"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.0", features = ["full"] }
image = "0.25"
anyhow = "1.0"
async-trait = "0.1"
parking_lot = "0.12"
